### ISSUE TITLE
Issue with POST comments=[{...}]

### ISSUE THREAD

**Issue by keithand** [keithand/origami-project#1]
In the command line, when I try to add a comment to an Item within the schema “comments:[{body:String, date:Date}]”, my DB still shows that the comment is undefined. I have tried several ways with httpie to code the comment, but nothing has proved successful. This was the last attempt I made in the command line:

$http POST localhost:9000 name=hello item=hello comments=[{“body”:”Hello Please Work!”}]

This is the error I get: TypeError: Cannot use 'in' operator to search for '_id

Do you have any idea what the problem might be?

**Comment by keithand** [comment]
I also identified the two potential errors that you did. I assume that this issue is with httpie, since the code I am using in my items.js file is the same as <a href="http://marker.to/FGi7Jj" target="_blank">the syntax that mongoose docs uses.</a> 

I figured it out. My httpie syntax was wrong. This is how I fixed it: 

http POST localhost:9000 name=Keith item=Me author=you comments:='[{"body":"Hello?"}]'

It took me long enough to figure this out! This is a lesson of reading the docs more thoroughly.

**Comment by jenius** [comment]
Awesome! So glad you dug in and figured this out on your own. It must have felt great to finally get it working :grinning:

**Comment by keithand** [comment]
It felt empowering. I started working on the application interface too. I haven’t started the front-end coding yet because I want to be 100% sure of the interface. See attached.

Keith

On Jan 3, 2015, at 10:47 AM, Jeff Escalante <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome! So glad you dug in and figured this out on your own. It must have felt great to finally get it working [:grinning:]

—
Reply to this email directly or view it on GitHub<https://github.com/keithand/origami-project/issues/1#issuecomment-68604977>.

Keith Anderson
ESL Testing Coordinator
Academy of Art University
79 New Montgomery St.
Room # 340
San Francisco, CA 94105
Phone#:(415)-618-8436

"The purpose of life is to be happy."

-Dalai Lama

**Comment by jenius** [comment]
You can't attach things to emails and send them to github. You need to come to github where the issue is and attach it there :grinning:

**Comment by keithand** [comment]
Ah ok. Still getting used to github. Earlier, I was trying to highlight code in my project to give the original message context, but wasn't able to figure it out in the issue panel.

Let me know what you think of the interface. I started this yesterday, but haven't fleshed everything 
![origami_interface_draft_page_1](https://cloud.githubusercontent.com/assets/6385008/5604286/d3cba4f8-9367-11e4-91d7-473ee9b73d0b.jpg)
![origami_interface_draft_page_2](https://cloud.githubusercontent.com/assets/6385008/5604287/d3cf8f50-9367-11e4-908e-2cd52b478023.jpg)
![origami_interface_draft_page_3](https://cloud.githubusercontent.com/assets/6385008/5604288/d3d0fe80-9367-11e4-8583-55e878692fb2.jpg)
![origami_interface_draft_page_4](https://cloud.githubusercontent.com/assets/6385008/5604289/d3d1a006-9367-11e4-8f61-2360d556c183.jpg)

**Comment by jenius** [comment]
Ok so as far as the interfacer, I don't understand what much of it is doing. The buttons up top are not labelled, which makes it pretty confusing, and I wouldn't really know that you could click on the words to open a new list.

I also might tone down some of the dimensionality just a little bit. Like, the drop shadows on the icons are probably not necessary, and sticking with a flatter background might make it a little more easy to figure out visually.

All that said, this is good progess! Usually on github if you are transitioning to a different issue, you open a new issue to talk about it. Want to maybe open up a "designs" issue so we can bring everything there in one place?

**Comment by keithand** [comment]
Good idea. :)

On Jan 3, 2015, at 6:08 PM, Jeff Escalante <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok so as far as the interfacer, I don't understand what much of it is doing. The buttons up top are not labelled, which makes it pretty confusing, and I wouldn't really know that you could click on the words to open a new list.

I also might tone down some of the dimensionality just a little bit. Like, the drop shadows on the icons are probably not necessary, and sticking with a flatter background might make it a little more easy to figure out visually.

All that said, this is good progess! Usually on github if you are transitioning to a different issue, you open a new issue to talk about it. Want to maybe open up a "designs" issue so we can bring everything there in one place?

—
Reply to this email directly or view it on GitHub<https://github.com/keithand/origami-project/issues/1#issuecomment-68617748>.

Keith Anderson
ESL Testing Coordinator
Academy of Art University
79 New Montgomery St.
Room # 340
San Francisco, CA 94105
Phone#:(415)-618-8436

"The purpose of life is to be happy."

-Dalai Lama
